CREATE WAREHOUSE COMPUTE_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE SUPPORT_ANALYTICS_DB;

USE DATABASE SUPPORT_ANALYTICS_DB;

CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA MART;


--ACCOUNTS TABLE

CREATE OR REPLACE TABLE RAW.ACCOUNTS (
    ACCOUNT_ID STRING,
    ACCOUNT_NAME STRING,
    INDUSTRY STRING,
    SEGMENT STRING,
    COUNTRY STRING,
    CREATED_DATE DATE
);

--AGENTS

CREATE OR REPLACE TABLE RAW.AGENTS (
    AGENT_ID STRING,
    AGENT_NAME STRING,
    TEAM STRING,
    MANAGER STRING,
    LOCATION STRING,
    HIRE_DATE DATE
);

--PRODUCTS

CREATE OR REPLACE TABLE RAW.PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    PRODUCT_CATEGORY STRING
);

--REGIONS

CREATE OR REPLACE TABLE RAW.REGIONS (
    REGION_ID STRING,
    REGION_NAME STRING
);

--SLA TARGETS

CREATE OR REPLACE TABLE RAW.SLA_TARGETS (
    PRIORITY STRING,
    SLA_HOURS NUMBER(10,0)
);

--CASES

CREATE OR REPLACE TABLE RAW.CASES (
    CASE_ID STRING,
    ACCOUNT_ID STRING,
    AGENT_ID STRING,
    PRODUCT_ID STRING,
    REGION_ID STRING,
    CREATED_DATE TIMESTAMP_NTZ,
    RESOLVED_DATE TIMESTAMP_NTZ,
    PRIORITY STRING,
    STATUS STRING,
    COMPLAINT_CATEGORY STRING,
    RESOLUTION_HOURS NUMBER(10,0),
    SLA_HOURS NUMBER(10,0),
    SLA_BREACH_FLAG NUMBER(1,0),
    REOPEN_FLAG NUMBER(1,0),
    ESCALATION_FLAG NUMBER(1,0)
);

--CASE ACTIVITIES

CREATE OR REPLACE TABLE RAW.CASE_ACTIVITIES (
    ACTIVITY_ID STRING,
    CASE_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_DATE TIMESTAMP_NTZ
);

--CUSTOMER FEEDBACK

CREATE OR REPLACE TABLE RAW.CUSTOMER_FEEDBACK (
    FEEDBACK_ID STRING,
    CASE_ID STRING,
    RATING NUMBER(1,0)
);

