CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE snowstage
FILE_FORMAT = CSV_FORMAT
URL = 's3://<your-bucket-name>/raw/';

-- ACCOUNTS
COPY INTO ACCOUNTS
FROM @snowstage
FILES = ('Accounts/accounts.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- AGENTS
COPY INTO AGENTS
FROM @snowstage
FILES = ('Agents/agents.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- ACTIVITIES
COPY INTO CASE_ACTIVITIES
FROM @snowstage
FILES = ('Activities/case_activities.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- CASES
COPY INTO CASES
FROM @snowstage
FILES = ('Cases/cases.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- FEEDBACK
COPY INTO CUSTOMER_FEEDBACK
FROM @snowstage
FILES = ('Feedbacks/customer_feedback.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- PRODUCTS
COPY INTO PRODUCTS
FROM @snowstage
FILES = ('Products/products.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- REGIONS
COPY INTO REGIONS
FROM @snowstage
FILES = ('Regions/regions.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

-- SLA TARGETS
COPY INTO SLA_TARGETS
FROM @snowstage
FILES = ('SLA-targets/sla_targets.csv')
CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
);

SELECT COUNT(*) FROM ACCOUNTS;
SELECT COUNT(*) FROM AGENTS;
SELECT COUNT(*) FROM PRODUCTS;
SELECT COUNT(*) FROM REGIONS;
SELECT COUNT(*) FROM SLA_TARGETS;
SELECT COUNT(*) FROM CASES;
SELECT COUNT(*) FROM CASE_ACTIVITIES;
SELECT COUNT(*) FROM CUSTOMER_FEEDBACK;