SELECT COUNT(*) FROM MART.FACT_CASE;

SELECT *
FROM MART.FACT_CASE;

SELECT * FROM MART.DIM_CUSTOMER;
SELECT * FROM MART.DIM_AGENT;
SELECT * FROM MART.DIM_PRODUCT;
SELECT * FROM MART.DIM_REGION;
SELECT * FROM MART.DIM_DATE;